# Generated by Django 5.0.1 on 2024-02-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='resposta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=10),
        ),
    ]
