# Generated by Django 5.0.1 on 2024-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_usuario_tipo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=10),
        ),
    ]
