# Generated by Django 5.0.1 on 2024-02-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_usuario_tipo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='paginas_compartilhadas',
            field=models.ManyToManyField(blank=True, related_name='paginas_compartilhadas', to='cards.pagina'),
        ),
    ]
