# Generated by Django 5.0.1 on 2024-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_usuario_paginas_compartilhadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='perfil/default.jpg', upload_to='perfil/'),
        ),
    ]
