# Generated by Django 5.0.1 on 2024-02-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('alternativa_a', models.TextField()),
                ('alternativa_b', models.TextField()),
                ('alternativa_c', models.TextField()),
                ('alternativa_d', models.TextField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulado', to='cards.pagina')),
            ],
        ),
    ]
