# Generated by Django 5.0.1 on 2024-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_simulados_respostas'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulados',
            name='correta',
            field=models.TextField(default='a'),
        ),
    ]
