# Generated by Django 5.0.1 on 2024-03-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_simulados_correta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulados',
            name='respostas',
        ),
    ]
