# Generated by Django 5.0.1 on 2024-03-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_remove_simulados_respostas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_simulado', to='cards.pagina')),
                ('questoes_corretas', models.ManyToManyField(blank=True, related_name='tentativas_corretas', to='cards.simulados')),
                ('questoes_erradas', models.ManyToManyField(blank=True, related_name='tentativas_erradas', to='cards.simulados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_simulado', to='cards.usuario')),
            ],
        ),
    ]
