# Generated by Django 5.0.1 on 2024-03-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_estatisticassimulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemRespostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('resposta', models.CharField()),
                ('numero_questao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticasEnem_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_usario', models.TextField()),
                ('correto_errada', models.BooleanField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_enem', to='cards.enemrespostas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enem_usuario', to='cards.usuario')),
            ],
        ),
    ]
