# Generated by Django 5.0.1 on 2024-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_enemrespostas_estatisticasenem_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemrespostas',
            name='espanhol',
            field=models.CharField(default='A'),
        ),
        migrations.AddField(
            model_name='enemrespostas',
            name='ingles',
            field=models.CharField(default='A'),
        ),
        migrations.AddField(
            model_name='estatisticasenem_usuario',
            name='idioma_escolhido',
            field=models.IntegerField(default=1),
        ),
    ]
