# Generated by Django 5.0.1 on 2024-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_enemrespostas_espanhol_enemrespostas_ingles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemrespostas',
            name='espanhol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enemrespostas',
            name='ingles',
            field=models.BooleanField(default=False),
        ),
    ]
